### ISSUE TITLE
Parsing error in config.yml

### ISSUE THREAD

**Issue by gpkvt** [conceptsandtraining/InstILIAS#2]
`expire_in_days:0` should be `expire_in_days: 0` in the default config.yml.

`PHP Fatal error:  Uncaught exception 'Symfony\Component\Yaml\Exception\ParseException' with message 'Unable to parse at line 213 (near "expire_in_days:0").' in /home/dwitt/test/InstILIAS/vendor/symfony/yaml/Parser.php:298
`

**Comment by shecken** [comment]
Thanks, i changed it.
