### ISSUE TITLE
Configuration of ilServer (java_server) incomplete

### ISSUE THREAD

**Issue by gpkvt** [conceptsandtraining/InstILIAS#4]
The config values for `java_server` are written correctly into the ILIAS database but the required ini-File for the ilServer.jar itself is missing. Most of the required values are already available from config.yml (IndexPath can be the same as data_dir, log path, client name, etc.), all other values are pretty much default values wo doesn't need to be changed.

```
[Server]
IpAddress = localhost
Port = 11111
IndexPath = /var/www/ilias/data/
LogFile = /var/log/ilias/ilServer.log
LogLevel = WARN
NumThreads = 1
RamBufferSize = 256
IndexMaxFileSizeMB = 500

[Client1]
ClientId = ACMECorp
NicId = 0
IliasIniPath = /var/www/html/ilias//ilias.ini.php

```

As a bonus InstILIAS may provide a proper init-Script for ilServer:

```
#!/bin/bash

JAVABIN=/usr/bin/java
ILIASDIR=/var/www/html/ilias    # Type in the root directory of your ILIAS installation
IL_SERVER_INI=/var/www/html/ilias/Services/WebServices/RPC/lib/ilServer.ini

case "$1" in
    start)
		echo "Starting ILIAS Java-Server"
        $JAVABIN -Dfile.encoding=UTF-8 -jar $ILIASDIR/Services/WebServices/RPC/lib/ilServer.jar $IL_SERVER_INI start &
		;;

    stop)
        echo "Shutting down ILIAS Java-Server"
        $JAVABIN -jar $ILIASDIR/Services/WebServices/RPC/lib/ilServer.jar $IL_SERVER_INI stop
        ;;
        
    status)
        $JAVABIN -jar $ILIASDIR/Services/WebServices/RPC/lib/ilServer.jar $IL_SERVER_INI status
        ;;    	

    restart)
        $0 stop
        sleep 2
        $0 start
        ;;

    *)
        echo "Usage: $0 {start|stop|status|restart}"
        exit 1
esac

exit 0
```

**Comment by shecken** [comment]
ilServer configuration i now complete.
We will think about the bash. Thanks for the advice.

**Comment by gpkvt** [comment]
By "bash" you mean the init-Script? I just noticed that, at least with ILIAS 5.1.x, the init-Script is available via `./Services/WebServices/RPC/lib/README.txt`

As the script should be run as Apache-User it usually hasn't the access rights to put the init-Script into `/etc/init.d/` so manual interaction would be needed anyway. So maybe a hint to the script provided by ILIAS is just fine. 

On the other hand it would be much nicer to run InstILIAS as root and fix the access rights during the installation. The username/group to be used could be an option in `config.yml`. This also would made the location for the logfiles/data folder more flexible as the Apache user doesn't need to have permissions to create the chosen folder and can chown them afterwards. Running InstILIAS as root would also enable us to install missing packages (like `mysqli`) automatically (at least for the major distributions). What do you think? Shall I create another Issue for this?
