### ISSUE TITLE
Script crashes if user already exists

### ISSUE THREAD

**Issue by gpkvt** [conceptsandtraining/InstILIAS#5]
If you chose to create an user who already exists in the database the script will fail to complete:

```
[Native code: 1062]
[Native message: Duplicate entry 'dwitt' for key 'uc1_idx']
<br />#0 /var/www/html/ilias/Services/Database/classes/class.ilDB.php(1599): ilDB->handleError(Object(MDB2_Error), 'manipulate(INSE...')
```

Existing Users should either be ignored or updated.

**Comment by shecken** [comment]
Check if user exists implemented.
You got an output with an advice that user is existing and no new was created.
